### ISSUE TITLE
Moodboard

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#1]

**Comment by ufuomaerh** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=0%3A1&t=qy6GuVQIox0O8BFk-1

**Comment by wemmy-UX** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=0%3A1&t=WS2hH9Oi26MAsv0z-1

**Comment by wemmy-UX** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=0%3A1&t=VWEXy6eYsHh9Vz9I-1

**Comment by Amychy** [comment]
Great
