### ISSUE TITLE
Profile settings

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#13]

**Comment by Gerald-TM** [comment]
Designed the Profile settings page using HTML and CSS.

Code: https://github.com/zuri-training/Reindeer2-T_c_gen/blob/main/templates/project_tc_gen/profile.html

Preview:

![Profile settings page](https://user-images.githubusercontent.com/105176000/209137115-ce173639-e5c4-41d7-b795-60cf75ecf1d2.png)

**Comment by Amychy** [comment]
Cool, please do the mobile view
