### ISSUE TITLE
Design sketch

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#2]

**Comment by AlabiOluwafemi** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=0%3A1&t=lfcPkLkLpkB3hwT0-1


Setting page 
Error page 
Dashboard
Generate t&c/ privacy policy
Verification
About us 
Company profile
Landing page

**Comment by ebukaobiajulu** [comment]
Did the sketches illustration using Adobe Illustrator
https://drive.google.com/drive/folders/1BGBBXP63wqvaOeTGZJkcb8yDZ9ZlvuX5

**Comment by Pooma2002** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=160%3A2&t=lfcPkLkLpkB3hwT0-1

Sign in page
Sign up page
About us page
Terms and conditions page
FAQ Page
Contact us page

**Comment by Amychy** [comment]
Good one guys
