### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#3]

**Comment by Gerald-TM** [comment]
**Database Schema Diagram** 
(https://drive.google.com/file/d/1uX3HpiBleFBdgTL8xVYwqA_c238sI6fo/view?usp=share_link)

![QuickDBD-t_c_gen database schema (2)](https://user-images.githubusercontent.com/105176000/205489887-eb529bc8-8683-44fd-aadc-165ddbbb885b.png)

**Comment by tohmyy** [comment]
Clarified **database schema** with team members via google meet. Brainstormed and collaborated with @Gerald-TM and other team members to gather knowledge which was utilized in the creation of the **database schema**

**Comment by Amychy** [comment]
Nice one
