### ISSUE TITLE
Files page

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#30]

**Comment by Gerald-TM** [comment]
Designed the files page using HTML and CSS.

Code: https://github.com/zuri-training/Reindeer2-T_c_gen/blob/main/templates/project_tc_gen/files.html

Preview

![Files page](https://user-images.githubusercontent.com/105176000/209138676-cd349fd4-4b90-40ee-af4e-3e5041e4fd4f.png)

**Comment by Amychy** [comment]
Ok great, please work on the mobile view
