### ISSUE TITLE
Generate template page

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#31]

**Comment by Gerald-TM** [comment]
Designed the generate templates page using HTML and CSS.

Code: https://github.com/zuri-training/Reindeer2-T_c_gen/blob/main/templates/project_tc_gen/projects.html

Preview:

![Generate templates page](https://user-images.githubusercontent.com/105176000/209138289-3a4d6bea-b358-4e75-8db5-6daf03bf8f8e.png)

**Comment by Amychy** [comment]
Ok cool, please work on the mobile view
