### ISSUE TITLE
Design - All other tablet high fi/  low fi

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#44]

**Comment by wemmy-UX** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=196%3A2&t=pnBEoz6FJQP4BeJC-1

**Comment by wemmy-UX** [comment]
![image](https://user-images.githubusercontent.com/119746413/208880026-66b5cff2-9baa-4423-ab10-9d0f8ee556bb.png)

**Comment by Amychy** [comment]
Thank you
