### ISSUE TITLE
User  story and User flow

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#5]

**Comment by Abiola-Olajide** [comment]
[https://www.figma.com/file/Iolyzj4mg4VIWqG1lY8u2j/User-Story-and-flow---Team-Reindeer2?node-id=0%3A1&t=jXyiyOVPwCMBNBrR-1](url)

**Comment by Abiola-Olajide** [comment]
For the User Research 

[https://www.figma.com/file/WBV3ZS1ZR6WkugDakOVGDf/User-Research---Team-Reindeer2?node-id=0%3A1&t=msrvu3R1qTudVqWk-1](url)

**Comment by goodnesskalu** [comment]
Completed user flow.

**Comment by Amychy** [comment]
All done
