### ISSUE TITLE
Design - Contact us

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#53]

**Comment by wemmy-UX** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=305%3A2075&t=pnBEoz6FJQP4BeJC-1

**Comment by Pooma2002** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=293%3A2113&t=pnBEoz6FJQP4BeJC-1

**Comment by Amychy** [comment]
Thank you
