### ISSUE TITLE
Design - Error page

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#59]

**Comment by wemmy-UX** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=640%3A4065&t=pnBEoz6FJQP4BeJC-1

**Comment by AlabiOluwafemi** [comment]
https://www.figma.com/file/ldZ4NLlErRm6vs4EVBqVM8/Team-Reindeer2?node-id=196%3A2&t=0AWNSsP43JwlBSCy-1
i designed the sketch and low fi for error page

**Comment by Amychy** [comment]
Thank you
