### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by Amychy** [zuri-training/Reindeer2-T_c_gen#6]

**Comment by Abiola-Olajide** [comment]
Done with user research

[https://www.figma.com/file/WBV3ZS1ZR6WkugDakOVGDf/User-Research---Team-Reindeer2?node-id=0%3A1&t=vR9ALKT5MnIZNzTW-1](url)

**Comment by goodnesskalu** [comment]
Completed user research. Nice work team!

**Comment by Amychy** [comment]
The research is complete
